### PR TITLE
Fix bug saved palettes

### PR DESCRIPTION
**Pull request by laurelbonal**
# Pull Request
## Description
fix bug in data model that was deleting the wrong saved palette when palettes were deleted 
## Related Issues
resolves issue with data model 
## Screenshots (if applicable)
n/a
## Changes Made
refactored functions and added id for boxes that allows us to delete the correct palette from the data model
## Testing
n/a
 ## Checklist
- [ x] The code follows the project's coding standards.
- [ ] Unit tests have been added or updated to cover the changes.
- [ x] Documentation has been updated to reflect the changes (if applicable).
- [ x] The code compiles without errors.
- [x ] The changes have been tested locally and pass all relevant tests.
- [ ] All new and existing tests pass.
- [ x] The pull request has been reviewed by at least one other contributor.
## Reviewer Instructions
n/a
## Deployment Notes
n/a
## Additional Information
n/a

### CODE REVIEW

**Review by BrandonDoza — COMMENTED** [review]
The code compiles without errors and looks clean and DRY. Nice problem solving skills to fix the bugs.

**Review by zachwolek — APPROVED** [review]
The editing was done within a live Zoom chat and communally agreed upon

**Comment by zachwolek** [comment]
Looks great and solved the issue of unique ID

**Review by Swatzell — APPROVED** [review]
Great work guys. It was a pleasure working with yall on this project

**Pull request merged**
