### PR TITLE
Add basic html layout

### PR DESCRIPTION
**Pull request by laurelbonal**
# Pull Request
## Description
provide basic outline of html and the boilerplate
## Related Issues
Resolves issue of not having html
## Screenshots (if applicable)
n/a
## Changes Made
created html layout with header, body, and divisions as well as linked html with js and css
## Testing
opened webpage to see layout
## Checklist
- [x] The code follows the project's coding standards.
- [ ] Unit tests have been added or updated to cover the changes.
- [x] Documentation has been updated to reflect the changes (if applicable).
- [x] The code compiles without errors.
- [x] The changes have been tested locally and pass all relevant tests.
- [ ] All new and existing tests pass.
- [x] The pull request has been reviewed by at least one other contributor.
## Reviewer Instructions
please look over html and open in browser
## Deployment Notes
n/a
## Additional Information
done with entire group

### CODE REVIEW

**Comment by BrandonDoza** [comment]
HTML looks clean and semantic tags were used. Nice work team!

**Review by BrandonDoza — COMMENTED** [review]
Looks great!

**Review by Swatzell — APPROVED** [review]
Well done Laurel! Everything looks good and clean to me

**Review by zachwolek — COMMENTED** [review]
This was done within group live over Zoom

**Pull request merged**
